### ISSUE TITLE
Make top user command based on the time listened, not the amount of songs.

### ISSUE THREAD

**Issue by juliarn** [Biospheere/spoticord#71]
The top user command should sort the user by their time listened to spotify, not the amount of the songs listened too.
Songs have different lenghts and listening to very short songs will make you higher in the ranking, although others listened longer to spotify.

**Comment by Biospheere** [comment]
There is already a command for that which lists top ten users based on the time they listened to their tracks. Because top command is going to be replaced by two other commands due to #70 the issue is not longer relevant imo.  
`+time server`
